### ISSUE TITLE
Phyml error

### ISSUE THREAD

**Issue by PHemarajata** [DHQP/SNVPhyl_Nextflow#1]
Hi! I ran into an error during the Phyml step. Please see below:
```
Error executing process > 'PHYML (1)'

Caused by:
  Process `PHYML (1)` terminated with an error exit status (132)

Command executed:

  phyml -i snvAlignment.phy --datatype nt --model GTR -v 0.0 -s BEST --ts/tv e --nclasses 4 --alpha e --bootstrap -4 --quiet
  mv snvAlignment.phy_phyml_stats.txt phylogeneticTreeStats.txt
  mv snvAlignment.phy_phyml_tree.txt phylogeneticTree.newick

Command exit status:
  132

Command output:
  (empty)

Command error:
  .command.sh: line 2: 382243 Illegal instruction     (core dumped) phyml -i snvAlignment.phy --datatype nt --model GTR -v 0.0 -s BEST --ts/tv e --nclasses 4 --alpha e --bootstrap -4 --quiet

Work dir:
  /home/peerahemarajata/SNVPhyl_Nextflow/work/80/f348a74a1f4fb5b24e54eb6b3951ab

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

Thank you!

**Comment by jvhagey** [comment]
Hi @PHemarajata,

This looks like its an error with PhyML and not this pipeline. Can you provided the error and out files from this run and a description of the dataset. You can find the error and out files in the working directory listed `/home/peerahemarajata/SNVPhyl_Nextflow/work/80/f348a74a1f4fb5b24e54eb6b3951ab/. command.err` and `/home/peerahemarajata/SNVPhyl_Nextflow/work/80/f348a74a1f4fb5b24e54eb6b3951ab/.command.out`.

**Comment by PHemarajata** [comment]
.command.err
```
/home/peerahemarajata/SNVPhyl_Nextflow/work/80/f348a74a1f4fb5b24e54eb6b3951ab/.command.sh: line 2: 382243 Illegal instruction     (core dumped) phyml -i snvAlignment.phy --datatype nt --model GTR -v 0.0 -s BEST --ts/tv e --nclasses 4 --alpha e --bootstrap -4 --quiet
```

.command.out is totally empty.

The dataset is 4 paired end ILM samples with one reference. The phylip output from the pipeline that was used in this step is attached.
[snvAlignment.zip](https://github.com/DHQP/SNVPhyl_Nextflow/files/8592797/snvAlignment.zip)

**Comment by jvhagey** [comment]
This is fixed with https://github.com/StaPH-B/docker-builds/issues/589
